services:
  broker:
    image: eclipse-mosquitto
    ports:
      - 1883:1883
      - 8883:8883
      - 9001:9001
    volumes:
      - ./mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - mosquitto_data:/mosquitto/data
      - mosquitto_log:/mosquitto/log
    networks:
      - iot_network

  mongodb:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: universe
      MONGO_INITDB_DATABASE: iotworld
    ports:
      - '27017-27019:27017-27019'
    volumes:
      - ./mongo-settings/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - iot_network

  datastore:
    image: datastore
    build:
      context: ./datastore/
      dockerfile: Dockerfile
    ports:
      - 5003:5000
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=universe
      - MONGO_INITDB_DATABASE=iotworld
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:5000
    depends_on:
      - mongodb
      - broker
    networks:
      - iot_network

  sensor:
    image: iotsensor
    build:
      context: ./iotsensor/
      dockerfile: Dockerfile
    depends_on:
      - broker
    networks:
      - iot_network

  iotservice:
    image: iotservice
    build:
      context: ./iotservice/
      dockerfile: Dockerfile
    depends_on:
      - broker
    networks:
      - iot_network

  web:
    image: dashboard
    build:
      context: ./dashboard/
      dockerfile: Dockerfile
    depends_on:
      - broker
    ports:
      - 4200:80
    networks:
      - iot_network
 
  pmengine:
    image: pmengine
    build:
      context: ./pm-engine/
      dockerfile: Dockerfile
    depends_on:
      - broker
    networks:
      - iot_network

networks:
  iot_network:
    driver: bridge

volumes:
  mosquitto_data:
  mosquitto_log:
